# We want to package to a specific S3 file path for this project

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        description: "Directory containing the project files."
        default: ""
      artifact-name:
        required: false
        type: string
        description: "Name of the artifact storing the build files."
      artifact-path:
        required: false
        type: string
        description: "Path where files should be zipped from"
        default: ""
      zip-file-name:
        required: false
        type: string
        description: "Name of the zip file to upload."
        default: ""
      s3-bucket-name:
        required: false
        type: string
        description: "Name of the S3 bucket to upload to."
        default: ""
      aws-region:
        required: false
        type: string
        description: "AWS region to use."
        default: 'eu-west-1'

name: Upload Deployable to S3

permissions:
  id-token: write
  contents: read

jobs:
  upload-zip-to-s3:
    name: Upload zip to S3
    environment: Service
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts if specified
        if: inputs.artifact-name != ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: "./temp-artifact"

      - name: Create zip file if not specified
        if: inputs.zip-file-name == ''
        run: |
          ZIP_FILE="$(pwd)/artifact.zip"

          if [ -d "./temp-artifact" ]; then
            # Navigate to artifact directory (with optional subdirectory)
            if [ -n "${{ inputs.artifact-path }}" ]; then
              cd "./temp-artifact/${{ inputs.artifact-path }}"
            else
              cd "./temp-artifact"
            fi
          fi

          zip -r "$ZIP_FILE" ./*

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_DEPLOYMENT_ROLE_NAME }}"

      - name: Upload to S3
        env:
          S3_BUCKET: ${{ inputs.s3-bucket-name != '' && inputs.s3-bucket-name || format('{0}-deployment-delivery-pipeline-artifacts', vars.AWS_ACCOUNT_ID) }}
          GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          ZIP_FILE_NAME: ${{ inputs.zip-file-name != '' && inputs.zip-file-name || format('{0}.zip', 'artifact') }}
        run: |
          S3_URI="s3://$S3_BUCKET/preview-url-mapper/main.zip"

          aws s3 cp "./$ZIP_FILE_NAME" "${S3_URI}" --metadata "tags"="'[\"${GIT_SHA}-SHA\",\"${BRANCH}-branch\"]'"
