on:
  push:
    branches:
      - main

name: CI/CD

jobs:
  build:
    uses: nsbno/platform-actions/.github/workflows/build.python.yml@v2
    secrets: inherit
    with:
      working-directory: './lambda-function'

  package:
    uses: nsbno/platform-actions/.github/workflows/package.s3.yml@v2
    secrets: inherit
    needs: build
    with:
      aws-region: 'us-east-1'
      s3-bucket-name: '727832596008-lambda-at-edge-preview-mapper'
      artifact-name: ${{ needs.build.outputs.artifact-name }}

  deploy:
    needs:
      - package
    uses: nsbno/platform-actions/.github/workflows/deployment.all-environments-terraform.yml@v2
    secrets: inherit
    if: '!cancelled() && !contains(needs.*.results, ''failure'') && success()'
    with:
      working-directory: './lambda-function'
