on:
  push:
    branches:
      - main

name: CI/CD

jobs:
#  terraform-changes:
#    uses: nsbno/platform-actions/.github/workflows/helpers.find-changes.terraform.yml@main
#    secrets: inherit
#    with:
#      working-directory: './lambda-function'

  build:
    uses: nsbno/platform-actions/.github/workflows/build.python.yml@main
    secrets: inherit
    with:
      working-directory: './lambda-function'

  package:
    uses: nsbno/platform-actions/.github/workflows/package.s3.yml@main
    secrets: inherit
    needs: build
    with:
      aws-region: 'us-east-1'
      s3-bucket-name: '727832596008-lambda-at-edge-artifacts'
      application-name: 'preview-url-mapper'
      artifact-name: ${{ needs.build.outputs.artifact-name }}

  deploy:
    needs:
      - package
#      - terraform-changes
    uses: nsbno/platform-actions/.github/workflows/deployment.all-environments.yml@main
    secrets: inherit
    if: '!cancelled() && !contains(needs.*.results, ''failure'') && success()'
    with:
      applications: preview-url-mapper
      terraform-changes: ${{ needs.terraform-changes.outputs.has-changes }}
      working-directory: './lambda-function'
      skip-service-environment: true
